import os from 'os';

export interface ConfigOptions {
    alias?: string, // TODO: If not specified (and not token specified), raise a warning at bootstraping and set skip = true,
    token?: string, // TODO: if specified, takes priority over alias field. A JWT encapsulating alias and other settings to be passed as configuration options. It is generated by Rebrandly dashboard, user must copy it and paste here in the options.
    skip?: boolean,
    dryRun?: boolean,
    log?: (...data: any[]) => void,
}

const defaultOptions: ConfigOptions = {
    alias: os.hostname(), // TODO: remove default os.hostname()
    skip: false,
    dryRun: false,
    log: console.log,
}

export const parseOptions = (options?: ConfigOptions): ConfigOptions => {
    if (options) {
        return {
            ...defaultOptions,
            ...options,
        };
    }

    return { ...defaultOptions };
};
